name: Deploy to gihub.io

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout react-cv repo
      uses: actions/checkout@v3
    - run: ls
    
    - name: Pull submodule git.io
      run: git submodule update --init build
    
    - name: Npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm run build
    
    - name: Update submodule
      run: git submodule update build
    
    - name: Push
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        cwd: build
        tag_push: '--force'
