name: Deploy to gihub.io

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout react-cv repo
      uses: actions/checkout@v3
    - run: ls
    
    - name: Checkout github.io repo
      uses: actions/checkout@v3
      with:
        repository: b-ran/b-ran.github.io
        path: build
    - run: ls build
        
    - name: Npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm run build
    
    - name: Deploy
      working-directory: build
    - run: git status
