name: Deploy to gihub.io

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    environment: github.io
    runs-on: ubuntu-latest

    steps:
    - name: Checkout react-cv repo
      uses: actions/checkout@v3
    
    - name: Npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm run build
    
    - name: Push
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: main
        folder: build
        repository-name: b-ran/b-ran.github.io
        ssh-key: ${{ secrets.DEPLOY_KEY }}