name: Deploy to gihub.io

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout react-cv repo
      uses: actions/checkout@v3
    - run: ls
    
    - name: Pull submodule b-ran.github.io
      run: git submodule update --init b-ran.github.io
    
    - name: Npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm run build
    
    - name: Move build files
      working-directory: build
      run: cp -rf * ../b-ran.github.io
      
    
    - name: Push
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        cwd: b-ran.github.io
        tag_push: '--force'
